# Generated by Django 5.0.6 on 2024-06-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicoin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='favicoin',
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m'),
        ),
    ]
